service: vika

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  environment:
    VIKA_TOKEN: ${env:VIKA_TOKEN}

package:
  include:
    - tele_vika/**
  exclude:
    - node_modules/**
    - dynamo/**
    - .env
    - package.json
    - package-lock.json

functions:
  hello:
    handler: tele_vika.handler.vika
    events:
      - http:
          path: vika
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: spent
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: N
          - AttributeName: Timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:*:*:table/spent
        Roles:
          - Ref: IamRoleLambdaExecution
